---
- name: Deploy Openshift Nodes 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Deploy nodes in target vCenter
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ hostvars[item]['hostname'] }}.{{ domain_name }}"
        template: "{{ template_name }}"
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        folder: "{{ vcenter_folder }}"
        resource_pool: "{{ vcenter_resourcepool }}"
        state: poweredon
        wait_for_ip_address: yes
        disk:
        - size_gb: "{{ disk_size_GB }}"
          type: thin
          datastore: "{{ vcenter_datastore }}"
        - size_gb: "40"
          type: thin
          datastore: "{{ vcenter_datastore }}"
        customization:
          hostname: "{{ hostvars[item]['hostname'] }}" 
          domain: "{{ domain_name }}"
          dns_servers: "{{ dns_servers }}"
        networks:
        - name: "{{ vcenter_network }}"
          ip: "{{ hostvars[item]['ip'] }}"
          netmask: "{{ netmask }}"
          gateway: "{{ gateway }}"
        - name: k8-priv-iscsivm-network
      with_items: "{{ groups['nodes'] }}"
